# Server groups
# Config Variables

one:
 hostname: localhost
 server_port : 3000
 primary : 1
 mongodb_url: "mongodb://localhost:27017"

two:
 hostname: localhost
 server_port : 4000
 primary : 0
 mongodb_url: "mongodb://localhost:27017"


three:
 hostname: localhost
 server_port : 5000
 primary : 0
 mongodb_url: "mongodb://localhost:27017"

four:
 hostname: 192.168.0.2
 server_port : 3000
 primary : 1
 mongodb_url: "mongodb://localhost:27017"

five:
 hostname: 192.168.0.5
 server_port : 3000
 primary : 0
 mongodb_url: "mongodb://localhost:27017"


six:
 hostname: 192.168.0.6
 server_port : 3000
 primary : 0
 mongodb_url: "mongodb://localhost:27017"

LRUCapacity: 5

UPLOAD_SHARD_SIZE: 52428800



